import React, { useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { assets } from "../assets/assets";
import { backendUrl } from "../config";
import { PlusCircle, Upload, Sparkles, Wand2, Loader2, Trash2 } from "lucide-react";
import { removeImageBackground } from "../utils/removeBackground";

const inputClass = "w-full rounded-xl border border-slate-200 bg-slate-50/30 px-4 py-3 text-sm text-slate-900 outline-none transition duration-200 placeholder:text-slate-400 focus:bg-white focus:border-slate-950 focus:ring-4 focus:ring-slate-950/5";
const labelClass = "mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-500";

const Add = ({ token }) => {
  const [image1, setImage1] = useState(false);
  const [image2, setImage2] = useState(false);
  const [image3, setImage3] = useState(false);
  const [image4, setImage4] = useState(false);
  const [removingBgSlot, setRemovingBgSlot] = useState(null);
  const [isCustomCategory, setIsCustomCategory] = useState(false);

  const [form, setForm] = useState({
    name: "",
    description: "",
    category: "Fashion",
    subCategory: "",
    collection: "Women",
    brand: "",
    sku: "",
    price: "",
    stock: "",
    variants: "",
    tags: "",
    specifications: "",
  });

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const resetForm = () => {
    setImage1(false);
    setImage2(false);
    setImage3(false);
    setImage4(false);
    setForm({
      name: "",
      description: "",
      category: "Fashion",
      subCategory: "",
      collection: "Women",
      brand: "",
      sku: "",
      price: "",
      stock: "",
      variants: "",
      tags: "",
      specifications: "",
    });
  };

  const [aiLoading, setAiLoading] = useState(false);

  const generateAIDescription = async () => {
    if (!form.name) {
      toast.warning("Please enter a product name first.");
      return;
    }
    
    setAiLoading(true);
    try {
      const response = await axios.post(
        `${backendUrl}/api/product/generate-description`,
        {
          name: form.name,
          category: form.category,
          subCategory: form.subCategory,
          collection: form.collection,
          brand: form.brand,
          price: form.price,
          sizes: form.variants,
        },
        { headers: { token } }
      );

      if (response.data.success) {
        updateField("description", response.data.description);
        toast.success("Description generated by AI!");
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      console.log(error);
      toast.error(error.message);
    } finally {
      setAiLoading(false);
    }
  };

  const onSubmitHandler = async (e) => {
    e.preventDefault();

    try {
      const formData = new FormData();

      Object.entries({
        name: form.name,
        description: form.description,
        category: form.category,
        subCategory: form.subCategory,
        collection: form.collection,
        brand: form.brand,
        sku: form.sku,
        price: form.price,
        stock: form.stock,
        sizes: form.variants,
        tags: form.tags,
        specifications: form.specifications,
      }).forEach(([key, value]) => {
        formData.append(key, value);
      });

      if (image1) formData.append("image1", image1);
      if (image2) formData.append("image2", image2);
      if (image3) formData.append("image3", image3);
      if (image4) formData.append("image4", image4);

      const response = await axios.post(
        `${backendUrl}/api/product/add`,
        formData,
        { headers: { token } }
      );

      if (response.data.success) {
        toast.success(response.data.message);
        resetForm();
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      console.log(error);
      toast.error(error.message);
    }
  };

  const handleProductBgRemoval = async (slotId, currentImage, setter) => {
    if (!currentImage) return;
    setRemovingBgSlot(slotId);
    try {
      const { file: transparentFile } = await removeImageBackground(currentImage);
      setter(transparentFile);
      toast.success("Background stripped to transparent PNG! ✨");
    } catch (err) {
      console.error("BG removal failed:", err);
      toast.error("Failed to remove background from product image");
    } finally {
      setRemovingBgSlot(null);
    }
  };

  return (
    <form onSubmit={onSubmitHandler} className="space-y-6">
      <div className="w-full max-w-5xl rounded-2xl border border-slate-200/80 bg-white dark:bg-slate-900 p-8 md:p-10 shadow-sm">
        
        {/* Header Section */}
        <div className="flex items-center gap-3.5 mb-8 border-b border-slate-100 pb-6">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-slate-100 dark:text-white shadow-sm shadow-slate-950/10">
            <PlusCircle size={20} />
          </div>
          <div>
            <h2 className="text-xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">Add Product</h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Create a new catalog item with detailed descriptors, attributes, and stock counts.
            </p>
          </div>
        </div>

        {/* Media Upload Area */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-1.5">
            <h3 className={labelClass}>
              Product Images
            </h3>
            <span className="text-[11px] text-slate-400 font-medium">
              Click &ldquo;✨ Remove BG&rdquo; on any image to strip the background to transparent PNG
            </span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-2">
            {[
              [image1, setImage1, "image1", "Main Image"],
              [image2, setImage2, "image2", "Side Angle"],
              [image3, setImage3, "image3", "Back Angle"],
              [image4, setImage4, "image4", "Detail View"],
            ].map(([image, setter, id, label]) => (
              <div key={id} className="flex flex-col gap-1.5">
                <label 
                  htmlFor={id} 
                  className="group relative flex flex-col items-center justify-center h-28 rounded-xl border-2 border-dashed border-slate-200 dark:border-slate-800 hover:border-slate-400 bg-slate-50/50 hover:bg-slate-50 cursor-pointer overflow-hidden transition-all duration-200"
                >
                  {image ? (
                    <div className="absolute inset-0 p-2 flex items-center justify-center bg-white dark:bg-slate-900">
                      <img
                        className="h-full w-full object-contain rounded-lg transition duration-200 group-hover:scale-105"
                        src={URL.createObjectURL(image)}
                        alt=""
                      />
                      {removingBgSlot === id && (
                        <div className="absolute inset-0 bg-slate-950/70 flex flex-col items-center justify-center text-white z-10 gap-1 text-[10px] font-bold">
                          <Loader2 size={16} className="animate-spin text-indigo-400" />
                          <span>Stripping BG...</span>
                        </div>
                      )}
                      <div className="absolute inset-0 bg-slate-950/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded-lg">
                        <span className="text-[10px] font-bold text-slate-100 dark:text-white uppercase tracking-wider">Change</span>
                      </div>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center gap-1.5 p-3 text-center">
                      <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-slate-400 group-hover:bg-slate-900 group-hover:text-white transition duration-200">
                        <Upload size={14} />
                      </div>
                      <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">{label}</span>
                    </div>
                  )}
                  <input
                    type="file"
                    id={id}
                    hidden
                    onChange={(e) => setter(e.target.files[0])}
                  />
                </label>

                {image && (
                  <div className="flex items-center justify-between gap-1 px-1">
                    <button
                      type="button"
                      onClick={() => handleProductBgRemoval(id, image, setter)}
                      disabled={removingBgSlot === id}
                      className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white shadow-2xs transition-all cursor-pointer disabled:opacity-50"
                      title="Strip image background using AI"
                    >
                      <Sparkles size={10} />
                      <span>Remove BG</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => setter(false)}
                      className="text-[10px] text-rose-500 hover:text-rose-700 font-bold p-0.5 cursor-pointer"
                      title="Clear image"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Content Fields */}
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="space-y-4">
            <div>
              <label className={labelClass}>Product Name</label>
              <input
                type="text"
                value={form.name}
                onChange={(e) => updateField("name", e.target.value)}
                placeholder="e.g. Wireless Noise-Cancelling Headphones"
                className={inputClass}
                required
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label className="text-xs font-bold uppercase tracking-wider text-slate-500">Description</label>
                <button
                  type="button"
                  onClick={generateAIDescription}
                  disabled={aiLoading || !form.name}
                  className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-wider text-orange-600 hover:text-orange-700 disabled:text-slate-400 disabled:cursor-not-allowed transition duration-150 cursor-pointer"
                >
                  <Sparkles size={11} className={aiLoading ? "animate-spin" : ""} />
                  {aiLoading ? "Generating..." : "AI Generate"}
                </button>
              </div>
              <textarea
                rows="5"
                value={form.description}
                onChange={(e) => updateField("description", e.target.value)}
                placeholder="Describe the product features, materials, and unique details..."
                className={`${inputClass} resize-none`}
                required
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="block text-xs font-bold uppercase tracking-wider text-slate-500">Category</label>
                  <button
                    type="button"
                    onClick={() => {
                      setIsCustomCategory(!isCustomCategory);
                      if (!isCustomCategory && !form.category) updateField("category", "");
                    }}
                    className="text-[10px] font-black text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer"
                  >
                    {isCustomCategory ? "← Choose List" : "+ Custom"}
                  </button>
                </div>
                {isCustomCategory ? (
                  <input
                    type="text"
                    value={form.category}
                    onChange={(e) => updateField("category", e.target.value)}
                    placeholder="e.g. Vintage Leather, Smart IoT"
                    className={inputClass}
                    required
                  />
                ) : (
                  <select
                    value={form.category}
                    onChange={(e) => {
                      if (e.target.value === "__custom__") {
                        setIsCustomCategory(true);
                        updateField("category", "");
                      } else {
                        updateField("category", e.target.value);
                      }
                    }}
                    className={inputClass}
                  >
                    <optgroup label="Popular Core">
                      <option value="Fashion">Fashion</option>
                      <option value="Footwear">Footwear</option>
                      <option value="Electronics">Electronics</option>
                      <option value="Beauty">Beauty</option>
                      <option value="Fitness">Fitness</option>
                      <option value="Accessories">Accessories</option>
                      <option value="Home & Lifestyle">Home & Lifestyle</option>
                      <option value="Kids Collection">Kids Collection</option>
                    </optgroup>

                    <optgroup label="Apparel & Fashion">
                      <option value="Men's Fashion">Men's Fashion</option>
                      <option value="Women's Fashion">Women's Fashion</option>
                      <option value="Streetwear & Urban">Streetwear & Urban</option>
                      <option value="Ethnic & Traditional">Ethnic & Traditional</option>
                      <option value="Winter & Outerwear">Winter & Outerwear</option>
                      <option value="Activewear & Sportswear">Activewear & Sportswear</option>
                    </optgroup>

                    <optgroup label="Footwear & Sneakers">
                      <option value="Sneakers & Athletic">Sneakers & Athletic</option>
                      <option value="Casual Shoes">Casual Shoes</option>
                      <option value="Formal Shoes">Formal Shoes</option>
                      <option value="Boots & Outdoor">Boots & Outdoor</option>
                    </optgroup>

                    <optgroup label="Electronics & Tech">
                      <option value="Smartphones & Mobile">Smartphones & Mobile</option>
                      <option value="Audio & Headphones">Audio & Headphones</option>
                      <option value="Laptops & Computers">Laptops & Computers</option>
                      <option value="Smartwatches & Wearables">Smartwatches & Wearables</option>
                      <option value="Gaming & Consoles">Gaming & Consoles</option>
                      <option value="Cameras & Photography">Cameras & Photography</option>
                      <option value="Smart Home & Tech Gadgets">Smart Home & Tech Gadgets</option>
                    </optgroup>

                    <optgroup label="Beauty & Personal Care">
                      <option value="Beauty & Cosmetics">Beauty & Cosmetics</option>
                      <option value="Skincare & Bodycare">Skincare & Bodycare</option>
                      <option value="Haircare & Styling">Haircare & Styling</option>
                      <option value="Perfumes & Fragrances">Perfumes & Fragrances</option>
                      <option value="Men's Grooming">Men's Grooming</option>
                    </optgroup>

                    <optgroup label="Home, Living & Appliances">
                      <option value="Kitchen & Dining">Kitchen & Dining</option>
                      <option value="Furniture & Living">Furniture & Living</option>
                      <option value="Home Decor & Lighting">Home Decor & Lighting</option>
                      <option value="Bedding & Bath">Bedding & Bath</option>
                      <option value="Home Appliances">Home Appliances</option>
                    </optgroup>

                    <optgroup label="Sports, Fitness & Outdoor">
                      <option value="Fitness & Gym">Fitness & Gym</option>
                      <option value="Sports & Outdoor">Sports & Outdoor</option>
                      <option value="Cycling & Bicycles">Cycling & Bicycles</option>
                      <option value="Camping & Adventure">Camping & Adventure</option>
                    </optgroup>

                    <optgroup label="Luxury & Accessories">
                      <option value="Jewelry & Fine Accessories">Jewelry & Fine Accessories</option>
                      <option value="Luxury Watches">Luxury Watches</option>
                      <option value="Bags, Backpacks & Luggage">Bags, Backpacks & Luggage</option>
                      <option value="Eyewear & Sunglasses">Eyewear & Sunglasses</option>
                    </optgroup>

                    <optgroup label="Essentials & Lifestyle">
                      <option value="Books & Stationery">Books & Stationery</option>
                      <option value="Toys & Baby Care">Toys & Baby Care</option>
                      <option value="Groceries & Gourmet">Groceries & Gourmet</option>
                      <option value="Pet Supplies">Pet Supplies</option>
                      <option value="Health & Wellness">Health & Wellness</option>
                      <option value="Automotive & Tools">Automotive & Tools</option>
                      <option value="Gifts & Festive">Gifts & Festive</option>
                    </optgroup>

                    <option value="__custom__">+ Enter Custom Category...</option>
                  </select>
                )}
              </div>

              <div>
                <label className={labelClass}>Collection</label>
                <select
                  value={form.collection}
                  onChange={(e) => updateField("collection", e.target.value)}
                  className={inputClass}
                >
                  <option>Women</option>
                  <option>Men</option>
                  <option>Kid</option>
                  <option>Unisex</option>
                  <option>General</option>
                </select>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Subcategory</label>
                <input
                  type="text"
                  value={form.subCategory}
                  onChange={(e) => updateField("subCategory", e.target.value)}
                  placeholder="e.g. Shoes, Watch, Top"
                  className={inputClass}
                />
              </div>

              <div>
                <label className={labelClass}>Brand</label>
                <input
                  type="text"
                  value={form.brand}
                  onChange={(e) => updateField("brand", e.target.value)}
                  placeholder="e.g. Acme Corp"
                  className={inputClass}
                />
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Price (₹)</label>
                <input
                  type="number"
                  value={form.price}
                  onChange={(e) => updateField("price", e.target.value)}
                  placeholder="0"
                  className={inputClass}
                  required
                />
              </div>

              <div>
                <label className={labelClass}>Stock Quantity</label>
                <input
                  type="number"
                  value={form.stock}
                  onChange={(e) => updateField("stock", e.target.value)}
                  placeholder="0"
                  className={inputClass}
                  required
                />
              </div>
            </div>

            <div>
              <label className={labelClass}>SKU (Stock Keeping Unit)</label>
              <input
                type="text"
                value={form.sku}
                onChange={(e) => updateField("sku", e.target.value)}
                placeholder="e.g. CAT-HD-001"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Variants / Sizes</label>
              <input
                type="text"
                value={form.variants}
                onChange={(e) => updateField("variants", e.target.value)}
                placeholder="e.g. S, M, L or 128GB, 256GB"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Tags</label>
              <input
                type="text"
                value={form.tags}
                onChange={(e) => updateField("tags", e.target.value)}
                placeholder="e.g. premium, wireless, bestseller"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Specifications</label>
              <textarea
                rows="5"
                value={form.specifications}
                onChange={(e) => updateField("specifications", e.target.value)}
                placeholder="e.g. Material: Cotton, Warranty: 1 year, Weight: 250g"
                className={`${inputClass} resize-none`}
              />
            </div>
          </div>
        </div>

        {/* Submit */}
        <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
          <button
            type="submit"
            className="flex items-center gap-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-100 dark:text-white px-8 py-3.5 text-xs font-bold transition shadow-sm hover:shadow active:scale-98"
          >
            <PlusCircle size={15} />
            Publish Product
          </button>
        </div>
      </div>
    </form>
  );
};

export default Add;
