import React, { useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { assets } from "../assets/assets";
import { backendUrl } from "../config";
import { PlusCircle, Upload, Sparkles } from "lucide-react";

const inputClass = "w-full rounded-xl border border-slate-200 bg-slate-50/30 px-4 py-3 text-sm text-slate-900 outline-none transition duration-200 placeholder:text-slate-400 focus:bg-white focus:border-slate-950 focus:ring-4 focus:ring-slate-950/5";
const labelClass = "mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-500";

const Add = ({ token }) => {
  const [image1, setImage1] = useState(false);
  const [image2, setImage2] = useState(false);
  const [image3, setImage3] = useState(false);
  const [image4, setImage4] = useState(false);

  const [form, setForm] = useState({
    name: "",
    description: "",
    category: "Fashion",
    subCategory: "",
    collection: "Women",
    brand: "",
    sku: "",
    price: "",
    stock: "",
    variants: "",
    tags: "",
    specifications: "",
  });

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const resetForm = () => {
    setImage1(false);
    setImage2(false);
    setImage3(false);
    setImage4(false);
    setForm({
      name: "",
      description: "",
      category: "Fashion",
      subCategory: "",
      collection: "Women",
      brand: "",
      sku: "",
      price: "",
      stock: "",
      variants: "",
      tags: "",
      specifications: "",
    });
  };

  const [aiLoading, setAiLoading] = useState(false);

  const generateAIDescription = async () => {
    if (!form.name) {
      toast.warning("Please enter a product name first.");
      return;
    }
    
    setAiLoading(true);
    try {
      const response = await axios.post(
        `${backendUrl}/api/product/generate-description`,
        {
          name: form.name,
          category: form.category,
          subCategory: form.subCategory,
          collection: form.collection,
          brand: form.brand,
          price: form.price,
          sizes: form.variants,
        },
        { headers: { token } }
      );

      if (response.data.success) {
        updateField("description", response.data.description);
        toast.success("Description generated by AI!");
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      console.log(error);
      toast.error(error.message);
    } finally {
      setAiLoading(false);
    }
  };

  const onSubmitHandler = async (e) => {
    e.preventDefault();

    try {
      const formData = new FormData();

      Object.entries({
        name: form.name,
        description: form.description,
        category: form.category,
        subCategory: form.subCategory,
        collection: form.collection,
        brand: form.brand,
        sku: form.sku,
        price: form.price,
        stock: form.stock,
        sizes: form.variants,
        tags: form.tags,
        specifications: form.specifications,
      }).forEach(([key, value]) => {
        formData.append(key, value);
      });

      if (image1) formData.append("image1", image1);
      if (image2) formData.append("image2", image2);
      if (image3) formData.append("image3", image3);
      if (image4) formData.append("image4", image4);

      const response = await axios.post(
        `${backendUrl}/api/product/add`,
        formData,
        { headers: { token } }
      );

      if (response.data.success) {
        toast.success(response.data.message);
        resetForm();
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      console.log(error);
      toast.error(error.message);
    }
  };

  return (
    <form onSubmit={onSubmitHandler} className="space-y-6">
      <div className="w-full max-w-5xl rounded-2xl border border-slate-200/80 bg-white dark:bg-slate-900 p-8 md:p-10 shadow-sm">
        
        {/* Header Section */}
        <div className="flex items-center gap-3.5 mb-8 border-b border-slate-100 pb-6">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-900 text-slate-100 dark:text-white shadow-sm shadow-slate-950/10">
            <PlusCircle size={20} />
          </div>
          <div>
            <h2 className="text-xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">Add Product</h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Create a new catalog item with detailed descriptors, attributes, and stock counts.
            </p>
          </div>
        </div>

        {/* Media Upload Area */}
        <div className="mb-8">
          <h3 className={labelClass}>
            Product Images
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-2">
            {[
              [image1, setImage1, "image1"],
              [image2, setImage2, "image2"],
              [image3, setImage3, "image3"],
              [image4, setImage4, "image4"],
            ].map(([image, setter, id]) => (
              <label 
                key={id} 
                htmlFor={id} 
                className="group relative flex flex-col items-center justify-center h-28 rounded-xl border-2 border-dashed border-slate-200 dark:border-slate-800 hover:border-slate-400 bg-slate-50/50 hover:bg-slate-50 cursor-pointer overflow-hidden transition-all duration-200"
              >
                {image ? (
                  <div className="absolute inset-0 p-2 flex items-center justify-center bg-white dark:bg-slate-900">
                    <img
                      className="h-full w-full object-contain rounded-lg transition duration-200 group-hover:scale-105"
                      src={URL.createObjectURL(image)}
                      alt=""
                    />
                    <div className="absolute inset-0 bg-slate-950/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded-lg">
                      <span className="text-[10px] font-bold text-slate-100 dark:text-white uppercase tracking-wider">Change</span>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-1.5 p-3 text-center">
                    <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-slate-400 group-hover:bg-slate-900 group-hover:text-white transition duration-200">
                      <Upload size={14} />
                    </div>
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Upload</span>
                  </div>
                )}
                <input
                  type="file"
                  id={id}
                  hidden
                  onChange={(e) => setter(e.target.files[0])}
                />
              </label>
            ))}
          </div>
        </div>

        {/* Content Fields */}
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="space-y-4">
            <div>
              <label className={labelClass}>Product Name</label>
              <input
                type="text"
                value={form.name}
                onChange={(e) => updateField("name", e.target.value)}
                placeholder="e.g. Wireless Noise-Cancelling Headphones"
                className={inputClass}
                required
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label className="text-xs font-bold uppercase tracking-wider text-slate-500">Description</label>
                <button
                  type="button"
                  onClick={generateAIDescription}
                  disabled={aiLoading || !form.name}
                  className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-wider text-orange-600 hover:text-orange-700 disabled:text-slate-400 disabled:cursor-not-allowed transition duration-150 cursor-pointer"
                >
                  <Sparkles size={11} className={aiLoading ? "animate-spin" : ""} />
                  {aiLoading ? "Generating..." : "AI Generate"}
                </button>
              </div>
              <textarea
                rows="5"
                value={form.description}
                onChange={(e) => updateField("description", e.target.value)}
                placeholder="Describe the product features, materials, and unique details..."
                className={`${inputClass} resize-none`}
                required
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Category</label>
                <select
                  value={form.category}
                  onChange={(e) => updateField("category", e.target.value)}
                  className={inputClass}
                >
                  <option>Fashion</option>
                  <option>Electronics</option>
                  <option>Accessories</option>
                  <option>Footwear</option>
                  <option>Home</option>
                  <option>Beauty</option>
                </select>
              </div>

              <div>
                <label className={labelClass}>Collection</label>
                <select
                  value={form.collection}
                  onChange={(e) => updateField("collection", e.target.value)}
                  className={inputClass}
                >
                  <option>Women</option>
                  <option>Men</option>
                  <option>Kid</option>
                  <option>Unisex</option>
                  <option>General</option>
                </select>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Subcategory</label>
                <input
                  type="text"
                  value={form.subCategory}
                  onChange={(e) => updateField("subCategory", e.target.value)}
                  placeholder="e.g. Shoes, Watch, Top"
                  className={inputClass}
                />
              </div>

              <div>
                <label className={labelClass}>Brand</label>
                <input
                  type="text"
                  value={form.brand}
                  onChange={(e) => updateField("brand", e.target.value)}
                  placeholder="e.g. Acme Corp"
                  className={inputClass}
                />
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Price (₹)</label>
                <input
                  type="number"
                  value={form.price}
                  onChange={(e) => updateField("price", e.target.value)}
                  placeholder="0"
                  className={inputClass}
                  required
                />
              </div>

              <div>
                <label className={labelClass}>Stock Quantity</label>
                <input
                  type="number"
                  value={form.stock}
                  onChange={(e) => updateField("stock", e.target.value)}
                  placeholder="0"
                  className={inputClass}
                  required
                />
              </div>
            </div>

            <div>
              <label className={labelClass}>SKU (Stock Keeping Unit)</label>
              <input
                type="text"
                value={form.sku}
                onChange={(e) => updateField("sku", e.target.value)}
                placeholder="e.g. CAT-HD-001"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Variants / Sizes</label>
              <input
                type="text"
                value={form.variants}
                onChange={(e) => updateField("variants", e.target.value)}
                placeholder="e.g. S, M, L or 128GB, 256GB"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Tags</label>
              <input
                type="text"
                value={form.tags}
                onChange={(e) => updateField("tags", e.target.value)}
                placeholder="e.g. premium, wireless, bestseller"
                className={inputClass}
              />
            </div>

            <div>
              <label className={labelClass}>Specifications</label>
              <textarea
                rows="5"
                value={form.specifications}
                onChange={(e) => updateField("specifications", e.target.value)}
                placeholder="e.g. Material: Cotton, Warranty: 1 year, Weight: 250g"
                className={`${inputClass} resize-none`}
              />
            </div>
          </div>
        </div>

        {/* Submit */}
        <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
          <button
            type="submit"
            className="flex items-center gap-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-100 dark:text-white px-8 py-3.5 text-xs font-bold transition shadow-sm hover:shadow active:scale-98"
          >
            <PlusCircle size={15} />
            Publish Product
          </button>
        </div>
      </div>
    </form>
  );
};

export default Add;
