import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    search_placeholder: "Search products, brands, electronics, fashion, accessories...",
    search_button: "Search",
    ai_tryon: "AI Try-On",
    account: "Account",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    orders: "Orders",
    continue_shopping: "Continue Shopping",
    your_cart: "Your Cart",
    cart_empty: "Your cart is empty",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    proceed_checkout: "Proceed to Checkout",
    track_order: "Track Order",
    track_return: "Track Return",
    request_return: "Request Return",
    get_support: "Get Support",
    add_to_cart: "Add to Cart",
    buy_now: "Buy Now",
    sold_out: "Sold Out",
    welcome: "Welcome",
    my_orders: "My Orders",
    lifetime_orders: "Lifetime Orders",
    total_spent: "Total Investment",
    membership_level: "Membership Level",
    fitting_room: "Fitting Room",
    enter_fitting_room: "Enter Fitting Room",
    smart_studio: "Smart Studio",
    ai_tryon_title: "AI Virtual Try-On",
    ai_tryon_subtitle: "Visualize garments directly on yourself or model avatars instantly.",
    select_clothing_step: "1. Select Clothing Item",
    select_store_products: "Select from store products",
    choose_body_photo_step: "2. Choose Body Photo",
    model_presets: "Model Presets",
    upload_photo: "Upload Photo",
    upload_body_photo: "Upload body photo",
    upload_constraints: "PNG, JPG up to 10MB (prefer full body standing)",
    ai_processing: "AI Processing...",
    generate_virtual_fit: "Generate Virtual Fit",
    original_frame: "Original Frame",
    fitted_virtual_result: "Fitted Virtual Result",
    developer_demo_active: "Developer Demo Mode Active",
    download_photo: "Download Photo",
    add_fitted_to_cart: "Add Fitted Size to Cart",
    enter_dressing_room: "Enter the Dressing Room",
    dressing_room_desc: "Pick a garment from the store catalog, choose a body photo or select a model, and click generate to fit the clothes virtual.",
    please_login_vton: "Please login to use AI Try-On",
    please_select_clothing: "Please select a clothing item",
    please_upload_photo: "Please upload a photo first",
    ai_generation_complete: "AI Generation Complete!",
    ai_generation_failed: "AI Generation Failed",
    added_to_cart: "Added to cart!",
    session_expired: "Session expired. Please login again.",
    failed_add_cart: "Failed to add to cart",
    step_1: "Uploading your photo...",
    step_2: "Analyzing body shape & posture...",
    step_3: "Mapping clothing texture contours...",
    step_4: "Refining final details with diffusion...",
    rewards: "Rewards",
    deliveries: "Deliveries",
    active: "Active",
    arriving_today: "Arriving Today",
    all_delivered: "All Delivered",
    points_label: "Points",
    rewards_dashboard: "Rewards Dashboard",
    recent_activity: "Recent Activity",
    available_coupons: "Available Coupons",
    cashback_balance: "Cashback Balance",
    free_shipping: "Free Shipping Status",
    loyalty_benefits: "Loyalty Benefits"
  },
  hi: {
    search_placeholder: "उत्पाद, ब्रांड, इलेक्ट्रॉनिक्स, फैशन, एक्सेसरीज़ खोजें...",
    search_button: "खोजें",
    ai_tryon: "एआई ट्राई-ऑन",
    account: "खाता",
    login: "लॉगिन",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    orders: "ऑर्डर",
    continue_shopping: "खरीदारी जारी रखें",
    your_cart: "आपका कार्ट",
    cart_empty: "आपका कार्ट खाली है",
    subtotal: "उप-योग",
    shipping: "शिपिंग",
    total: "कुल",
    proceed_checkout: "चेकआउट के लिए आगे बढ़ें",
    track_order: "ऑर्डर ट्रैक करें",
    track_return: "रिटर्न ट्रैक करें",
    request_return: "रिटर्न अनुरोध",
    get_support: "सहायता प्राप्त करें",
    add_to_cart: "कार्ट में जोड़ें",
    buy_now: "अभी खरीदें",
    sold_out: "बिक गया",
    welcome: "स्वागत हे",
    my_orders: "मेरे ऑर्डर",
    lifetime_orders: "लाइफटाइम ऑर्डर",
    total_spent: "कुल खर्च",
    membership_level: "सदस्यता स्तर",
    fitting_room: "फ़िटिंग रूम",
    enter_fitting_room: "फ़िटिंग रूम में प्रवेश करें",
    smart_studio: "स्मार्ट स्टूडियो",
    ai_tryon_title: "एआई वर्चुअल ट्राई-ऑन",
    ai_tryon_subtitle: "कपड़ों को सीधे अपने ऊपर या मॉडल अवतारों पर तुरंत देखें।",
    select_clothing_step: "1. कपड़े का चयन करें",
    select_store_products: "स्टोर उत्पादों में से चुनें",
    choose_body_photo_step: "2. शरीर का फोटो चुनें",
    model_presets: "मॉडल प्रीसेट",
    upload_photo: "फोटो अपलोड करें",
    upload_body_photo: "शरीर का फोटो अपलोड करें",
    upload_constraints: "PNG, JPG 10MB तक (खड़े हुए पूरे शरीर का फोटो बेहतर है)",
    ai_processing: "एआई प्रोसेसिंग...",
    generate_virtual_fit: "वर्चुअल फिट जनरेट करें",
    original_frame: "मूल फ्रेम",
    fitted_virtual_result: "फिट किया गया वर्चुअल परिणाम",
    developer_demo_active: "डेवलपर डेमो मोड सक्रिय",
    download_photo: "फोटो डाउनलोड करें",
    add_fitted_to_cart: "फिट किया गया आकार कार्ट में जोड़ें",
    enter_dressing_room: "ड्रेसिंग रूम में प्रवेश करें",
    dressing_room_desc: "स्टोर कैटलॉग से एक कपड़ा चुनें, एक शरीर का फोटो चुनें या एक मॉडल चुनें, और वर्चुअल रूप से फिट करने के लिए जनरेट पर क्लिक करें।",
    please_login_vton: "कृपया एआई ट्राई-ऑन का उपयोग करने के लिए लॉगिन करें",
    please_select_clothing: "कृपया एक कपड़ा चुनें",
    please_upload_photo: "कृपया पहले एक फोटो अपलोड करें",
    ai_generation_complete: "एआई जनरेशन पूरा हुआ!",
    ai_generation_failed: "एआई जनरेशन विफल रहा",
    added_to_cart: "कार्ट में जोड़ा गया!",
    session_expired: "सत्र समाप्त हो गया। कृपया फिर से लॉगिन करें।",
    failed_add_cart: "कार्ट में जोड़ने में विफल",
    step_1: "आपका फोटो अपलोड किया जा रहा है...",
    step_2: "शरीर के आकार और मुद्रा का विश्लेषण किया जा रहा है...",
    step_3: "कपड़ों की बनावट की रूपरेखा तैयार की जा रही है...",
    step_4: "डिफ्यूज़न के साथ अंतिम विवरणों को बेहतर बनाया जा रहा है...",
    rewards: "पुरस्कार",
    deliveries: "डिलिवरी",
    active: "सक्रिय",
    arriving_today: "आज आ रहा है",
    all_delivered: "सभी वितरित",
    points_label: "अंक",
    rewards_dashboard: "पुरस्कार डैशबोर्ड",
    recent_activity: "हाल की गतिविधि",
    available_coupons: "उपलब्ध कूपन",
    cashback_balance: "कैशबैक बैलेंस",
    free_shipping: "मुफ़्त शिपिंग स्थिति",
    loyalty_benefits: "लॉयल्टी लाभ"
  },
  es: {
    search_placeholder: "Buscar productos, marcas, electrónica, moda, accesorios...",
    search_button: "Buscar",
    ai_tryon: "Probador IA",
    account: "Cuenta",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    profile: "Perfil",
    orders: "Pedidos",
    continue_shopping: "Seguir Comprando",
    your_cart: "Tu Carrito",
    cart_empty: "Tu carrito está vacío",
    subtotal: "Subtotal",
    shipping: "Envío",
    total: "Total",
    proceed_checkout: "Proceder al Pago",
    track_order: "Seguir Pedido",
    track_return: "Seguir Devolución",
    request_return: "Solicitar Devolución",
    get_support: "Obtener Soporte",
    add_to_cart: "Añadir al Carrito",
    buy_now: "Comprar Ahora",
    sold_out: "Agotado",
    welcome: "Bienvenido",
    my_orders: "Mis Pedidos",
    lifetime_orders: "Pedidos Totales",
    total_spent: "Inversión Total",
    membership_level: "Nivel de Membresía",
    fitting_room: "Probador Virtual",
    enter_fitting_room: "Entrar al Probador",
    smart_studio: "Estudio Inteligente",
    ai_tryon_title: "Probador Virtual IA",
    ai_tryon_subtitle: "Visualiza prendas directamente en ti mismo o en avatares de modelos al instante.",
    select_clothing_step: "1. Seleccionar Prenda",
    select_store_products: "Seleccionar de los productos de la tienda",
    choose_body_photo_step: "2. Elegir Foto de Cuerpo",
    model_presets: "Modelos Preestablecidos",
    upload_photo: "Subir Foto",
    upload_body_photo: "Subir foto del cuerpo",
    upload_constraints: "PNG, JPG hasta 10MB (se prefiere de cuerpo entero de pie)",
    ai_processing: "Procesando IA...",
    generate_virtual_fit: "Generar Ajuste Virtual",
    original_frame: "Marco Original",
    fitted_virtual_result: "Resultado Virtual Ajustado",
    developer_demo_active: "Modo Demo de Desarrollador Activo",
    download_photo: "Descargar Foto",
    add_fitted_to_cart: "Añadir Talla Ajustada al Carrito",
    enter_dressing_room: "Entrar al Probador",
    dressing_room_desc: "Elige una prenda del catálogo de la tienda, elige una foto de cuerpo o selecciona un modelo, y haz clic en generar para probar la ropa virtualmente.",
    please_login_vton: "Por favor, inicia sesión para usar el Probador IA",
    please_select_clothing: "Por favor, selecciona una prenda",
    please_upload_photo: "Por favor, sube una foto primero",
    ai_generation_complete: "¡Generación IA Completada!",
    ai_generation_failed: "Generación IA Fallida",
    added_to_cart: "¡Añadido al carrito!",
    session_expired: "Sesión expirada. Por favor, inicia sesión de nuevo.",
    failed_add_cart: "Error al añadir al carrito",
    step_1: "Subiendo tu foto...",
    step_2: "Analizando la forma y postura del cuerpo...",
    step_3: "Mapeando contornos de la textura de la ropa...",
    step_4: "Refinando detalles finales con difusión...",
    rewards: "Recompensas",
    deliveries: "Entregas",
    active: "Activo",
    arriving_today: "Llega Hoy",
    all_delivered: "Todo Entregado",
    points_label: "Puntos",
    rewards_dashboard: "Panel de Recompensas",
    recent_activity: "Actividad Reciente",
    available_coupons: "Cupones Disponibles",
    cashback_balance: "Saldo Cashback",
    free_shipping: "Envío Gratis",
    loyalty_benefits: "Beneficios de Lealtad"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "en";
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
