import dotenv from "dotenv";
import mongoose from "mongoose";
import productModel from "../models/productModel.js";

dotenv.config();

const image = (query) =>
  `https://images.unsplash.com/${query}?auto=format&fit=crop&w=1200&q=80`;

const makeProduct = ({
  name,
  description,
  price,
  category,
  subCategory,
  collection = "General",
  brand,
  sku,
  stock,
  sizes = [],
  tags = [],
  specifications = [],
  images,
}) => ({
  name,
  description,
  price,
  category,
  subCategory,
  collection,
  brand,
  sku,
  stock,
  sizes,
  tags,
  specifications,
  images,
});

const products = [
  makeProduct({
    name: "Tailored Office Blazer",
    description: "A sharp structured blazer with clean lines and versatile layering for formal and smart-casual styling.",
    price: 3299,
    category: "Fashion",
    subCategory: "Blazer",
    collection: "Women",
    brand: "North Thread",
    sku: "FSH-W-BLZ-001",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    tags: ["formal", "premium", "office"],
    specifications: [
      { key: "Fabric", value: "Poly viscose blend" },
      { key: "Fit", value: "Tailored" },
    ],
    images: [
      image("photo-1551488831-00ddcb6c6bd3"),
      image("photo-1509631179647-0177331693ae"),
    ],
  }),
  makeProduct({
    name: "Weekend Resort Shirt",
    description: "Relaxed fit printed shirt designed for vacations, brunches, and easy summer layering.",
    price: 1399,
    category: "Fashion",
    subCategory: "Shirt",
    collection: "Men",
    brand: "North Thread",
    sku: "FSH-M-SHT-002",
    stock: 24,
    sizes: ["S", "M", "L", "XL"],
    tags: ["summer", "casual", "lightweight"],
    specifications: [
      { key: "Fabric", value: "Viscose cotton" },
      { key: "Sleeve", value: "Half sleeve" },
    ],
    images: [
      image("photo-1602810318383-e386cc2a3ccf"),
      image("photo-1603252109303-2751441dd157"),
    ],
  }),
  makeProduct({
    name: "Essential Straight Jeans",
    description: "Mid-rise straight denim with easy structure and all-day wear comfort.",
    price: 1799,
    category: "Fashion",
    subCategory: "Jeans",
    collection: "Women",
    brand: "Blue Harbor",
    sku: "FSH-W-JNS-003",
    stock: 30,
    sizes: ["28", "30", "32", "34"],
    tags: ["denim", "everyday", "wardrobe"],
    specifications: [
      { key: "Fit", value: "Straight" },
      { key: "Wash", value: "Mid blue" },
    ],
    images: [
      image("photo-1541099649105-f69ad21f3246"),
      image("photo-1542272604-787c3835535d"),
    ],
  }),
  makeProduct({
    name: "Classic Polo Tee",
    description: "Soft polo with rib collar and crisp silhouette for effortless smart-casual dressing.",
    price: 999,
    category: "Fashion",
    subCategory: "T-Shirt",
    collection: "Men",
    brand: "Crestline",
    sku: "FSH-M-TEE-004",
    stock: 35,
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["smart casual", "cotton", "daily"],
    specifications: [
      { key: "Fabric", value: "Cotton pique" },
      { key: "Neck", value: "Polo" },
    ],
    images: [
      image("photo-1586790170083-2f9ceadc732d"),
      image("photo-1620012253295-c15cc3e65df4"),
    ],
  }),
  makeProduct({
    name: "Everyday Cotton Kurta",
    description: "Breathable cotton kurta with minimal detailing and a flattering straight fall.",
    price: 1249,
    category: "Fashion",
    subCategory: "Kurta",
    collection: "Women",
    brand: "Saarth",
    sku: "FSH-W-KUR-005",
    stock: 26,
    sizes: ["S", "M", "L", "XL"],
    tags: ["ethnic", "cotton", "daily wear"],
    specifications: [
      { key: "Length", value: "Calf length" },
      { key: "Pattern", value: "Solid" },
    ],
    images: [
      image("photo-1594633312681-425c7b97ccd1"),
      image("photo-1502716119720-b23a93e5fe1b"),
    ],
  }),
  makeProduct({
    name: "Lightweight Bomber Jacket",
    description: "A modern bomber with streamlined finishing for mild weather and travel days.",
    price: 2899,
    category: "Fashion",
    subCategory: "Jacket",
    collection: "Men",
    brand: "Crestline",
    sku: "FSH-M-JKT-006",
    stock: 15,
    sizes: ["M", "L", "XL"],
    tags: ["outerwear", "layering", "urban"],
    specifications: [
      { key: "Closure", value: "Zip front" },
      { key: "Weight", value: "Lightweight" },
    ],
    images: [
      image("photo-1520975682031-a5a0f6d5bbd9"),
      image("photo-1520975867597-0af37a22e31e"),
    ],
  }),
  makeProduct({
    name: "Pleated Occasion Dress",
    description: "Elegant midi dress with pleated movement and subtle polish for dinners and events.",
    price: 2599,
    category: "Fashion",
    subCategory: "Dress",
    collection: "Women",
    brand: "Atelier June",
    sku: "FSH-W-DRS-007",
    stock: 12,
    sizes: ["S", "M", "L"],
    tags: ["occasion", "midi", "elegant"],
    specifications: [
      { key: "Length", value: "Midi" },
      { key: "Style", value: "Pleated" },
    ],
    images: [
      image("photo-1496747611176-843222e1e57c"),
      image("photo-1485968579580-b6d095142e6e"),
    ],
  }),
  makeProduct({
    name: "Kids Colorblock Hoodie",
    description: "Soft brushed hoodie with playful color blocking and comfortable fit for active days.",
    price: 899,
    category: "Fashion",
    subCategory: "Hoodie",
    collection: "Kid",
    brand: "Mini Miles",
    sku: "FSH-K-HOD-008",
    stock: 22,
    sizes: ["4Y", "6Y", "8Y", "10Y"],
    tags: ["kids", "cozy", "playtime"],
    specifications: [
      { key: "Fabric", value: "Cotton fleece" },
      { key: "Pockets", value: "Kangaroo pocket" },
    ],
    images: [
      image("photo-1503454537195-1dcabb73ffb9"),
      image("photo-1519238359922-989348752efb"),
    ],
  }),
  makeProduct({
    name: "Linen Blend Trousers",
    description: "Relaxed smart trousers with airy linen blend construction and neat tapered lines.",
    price: 1899,
    category: "Fashion",
    subCategory: "Trousers",
    collection: "Women",
    brand: "Atelier June",
    sku: "FSH-W-TRS-009",
    stock: 19,
    sizes: ["S", "M", "L", "XL"],
    tags: ["linen", "resort", "easy fit"],
    specifications: [
      { key: "Fit", value: "Relaxed tapered" },
      { key: "Waist", value: "Mid rise" },
    ],
    images: [
      image("photo-1506629905607-d9dd6f8f6833"),
      image("photo-1473966968600-fa801b869a1a"),
    ],
  }),
  makeProduct({
    name: "Oversized Everyday Tee",
    description: "Clean oversized tee with soft drape and minimal branding for street-ready basics.",
    price: 799,
    category: "Fashion",
    subCategory: "T-Shirt",
    collection: "Unisex",
    brand: "Basic Foundry",
    sku: "FSH-U-TEE-010",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    tags: ["oversized", "streetwear", "basic"],
    specifications: [
      { key: "Fabric", value: "Combed cotton" },
      { key: "Fit", value: "Oversized" },
    ],
    images: [
      image("photo-1521572163474-6864f9cf17ab"),
      image("photo-1503341504253-dff4815485f1"),
    ],
  }),

  makeProduct({
    name: "Nova X Pro Smartphone",
    description: "Flagship Android phone with bright OLED display, fast charging, and all-day battery life.",
    price: 54999,
    category: "Electronics",
    subCategory: "Smartphone",
    collection: "General",
    brand: "Nova",
    sku: "ELC-PHN-011",
    stock: 14,
    sizes: ["128GB", "256GB"],
    tags: ["5G", "flagship", "camera"],
    specifications: [
      { key: "Display", value: "6.7-inch OLED" },
      { key: "Battery", value: "5000mAh" },
      { key: "Camera", value: "50MP triple camera" },
    ],
    images: [
      image("photo-1511707171634-5f897ff02aa9"),
      image("photo-1598327105666-5b89351aff97"),
    ],
  }),
  makeProduct({
    name: "Pulse Active Earbuds",
    description: "True wireless earbuds with secure fit, powerful bass, and noise reduction for calls.",
    price: 4999,
    category: "Electronics",
    subCategory: "Audio",
    collection: "General",
    brand: "Pulse",
    sku: "ELC-AUD-012",
    stock: 34,
    sizes: ["Standard"],
    tags: ["wireless", "audio", "travel"],
    specifications: [
      { key: "Battery", value: "30 hours with case" },
      { key: "Connectivity", value: "Bluetooth 5.3" },
    ],
    images: [
      image("photo-1588423771073-b8903fbb85b5"),
      image("photo-1606220588913-b3aacb4d2f37"),
    ],
  }),
  makeProduct({
    name: "Vision 4K Smart TV",
    description: "Large-screen smart TV with crisp 4K visuals, streaming apps, and immersive sound tuning.",
    price: 68999,
    category: "Electronics",
    subCategory: "Television",
    collection: "General",
    brand: "Vision",
    sku: "ELC-TV-013",
    stock: 8,
    sizes: ["55-inch", "65-inch"],
    tags: ["smart tv", "4k", "home entertainment"],
    specifications: [
      { key: "Resolution", value: "4K UHD" },
      { key: "HDR", value: "Dolby Vision" },
    ],
    images: [
      image("photo-1593784991095-a205069470b6"),
      image("photo-1461151304267-38535e780c79"),
    ],
  }),
  makeProduct({
    name: "AeroBook Slim Laptop",
    description: "Portable performance laptop with premium metal design, long battery life, and vivid display.",
    price: 82999,
    category: "Electronics",
    subCategory: "Laptop",
    collection: "General",
    brand: "AeroBook",
    sku: "ELC-LTP-014",
    stock: 9,
    sizes: ["16GB/512GB", "16GB/1TB"],
    tags: ["work", "portable", "performance"],
    specifications: [
      { key: "Processor", value: "Intel Core Ultra 7" },
      { key: "Display", value: "14-inch 2.8K" },
    ],
    images: [
      image("photo-1496181133206-80ce9b88a853"),
      image("photo-1517336714739-489689fd1ca8"),
    ],
  }),
  makeProduct({
    name: "FrameView Monitor",
    description: "27-inch productivity monitor with sharp visuals, slim bezels, and ergonomic adjustments.",
    price: 21999,
    category: "Electronics",
    subCategory: "Monitor",
    collection: "General",
    brand: "FrameView",
    sku: "ELC-MON-015",
    stock: 11,
    sizes: ["27-inch"],
    tags: ["workspace", "display", "productivity"],
    specifications: [
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Refresh Rate", value: "144Hz" },
    ],
    images: [
      image("photo-1527443224154-c4a3942d3acf"),
      image("photo-1547082299-de196ea013d6"),
    ],
  }),
  makeProduct({
    name: "PowerDock Wireless Charger",
    description: "Minimal wireless charging station for phone, watch, and earbuds with tidy cable management.",
    price: 3499,
    category: "Electronics",
    subCategory: "Charging",
    collection: "General",
    brand: "Volt",
    sku: "ELC-CHR-016",
    stock: 27,
    sizes: ["3-in-1 Dock"],
    tags: ["wireless charging", "desk", "accessory"],
    specifications: [
      { key: "Output", value: "15W max" },
      { key: "Support", value: "Phone + watch + earbuds" },
    ],
    images: [
      image("photo-1583394838336-acd977736f90"),
      image("photo-1615526675051-f7a5d74a1f0d"),
    ],
  }),
  makeProduct({
    name: "SnapShot Mirrorless Camera",
    description: "Compact camera with detailed imaging, 4K recording, and intuitive controls for creators.",
    price: 95999,
    category: "Electronics",
    subCategory: "Camera",
    collection: "General",
    brand: "SnapShot",
    sku: "ELC-CAM-017",
    stock: 6,
    sizes: ["Body Only", "With Lens Kit"],
    tags: ["creator", "photography", "4k"],
    specifications: [
      { key: "Sensor", value: "24MP APS-C" },
      { key: "Video", value: "4K 60fps" },
    ],
    images: [
      image("photo-1516035069371-29a1b244cc32"),
      image("photo-1502920917128-1aa500764cbd"),
    ],
  }),
  makeProduct({
    name: "CoreSound Bluetooth Speaker",
    description: "Portable speaker with room-filling sound, water resistance, and deep battery endurance.",
    price: 6999,
    category: "Electronics",
    subCategory: "Speaker",
    collection: "General",
    brand: "CoreSound",
    sku: "ELC-SPK-018",
    stock: 21,
    sizes: ["Portable"],
    tags: ["speaker", "party", "portable"],
    specifications: [
      { key: "Battery", value: "20 hours" },
      { key: "Resistance", value: "IPX7" },
    ],
    images: [
      image("photo-1545454675-3531b543be5d"),
      image("photo-1512446733611-9099a758e0d0"),
    ],
  }),
  makeProduct({
    name: "SwiftPad Tablet",
    description: "Slim tablet with bright display and accessory support for reading, entertainment, and notes.",
    price: 32999,
    category: "Electronics",
    subCategory: "Tablet",
    collection: "General",
    brand: "SwiftPad",
    sku: "ELC-TAB-019",
    stock: 13,
    sizes: ["128GB", "256GB"],
    tags: ["tablet", "productivity", "media"],
    specifications: [
      { key: "Display", value: "11-inch LCD" },
      { key: "Battery", value: "8000mAh" },
    ],
    images: [
      image("photo-1585790050230-5dd28404ccb9"),
      image("photo-1561154464-82e9adf32764"),
    ],
  }),
  makeProduct({
    name: "GameBox Mechanical Keyboard",
    description: "Responsive mechanical keyboard with tactile switches, RGB lighting, and compact layout.",
    price: 5999,
    category: "Electronics",
    subCategory: "Keyboard",
    collection: "General",
    brand: "GameBox",
    sku: "ELC-KBD-020",
    stock: 17,
    sizes: ["75% Layout"],
    tags: ["gaming", "rgb", "mechanical"],
    specifications: [
      { key: "Switch Type", value: "Tactile" },
      { key: "Connectivity", value: "Wired USB-C" },
    ],
    images: [
      image("photo-1511467687858-23d96c32e4ae"),
      image("photo-1618384887929-16ec33fab9ef"),
    ],
  }),

  makeProduct({
    name: "Leather Travel Wallet",
    description: "Compact wallet with secure zip storage and organized slots for cards, cash, and travel documents.",
    price: 1699,
    category: "Accessories",
    subCategory: "Wallet",
    collection: "Unisex",
    brand: "Oak & Hide",
    sku: "ACC-WLT-021",
    stock: 28,
    sizes: ["Standard"],
    tags: ["leather", "travel", "daily carry"],
    specifications: [
      { key: "Material", value: "Genuine leather" },
      { key: "Compartments", value: "8 card slots" },
    ],
    images: [
      image("photo-1627123424574-724758594e93"),
      image("photo-1553062407-98eeb64c6a62"),
    ],
  }),
  makeProduct({
    name: "Classic Analog Watch",
    description: "Elegant analog watch with a minimalist dial and polished metal case for everyday sophistication.",
    price: 4999,
    category: "Accessories",
    subCategory: "Watch",
    collection: "Men",
    brand: "Chrona",
    sku: "ACC-WAT-022",
    stock: 20,
    sizes: ["40mm"],
    tags: ["watch", "formal", "classic"],
    specifications: [
      { key: "Strap", value: "Leather strap" },
      { key: "Movement", value: "Quartz" },
    ],
    images: [
      image("photo-1523170335258-f5ed11844a49"),
      image("photo-1434056886845-dac89ffe9b56"),
    ],
  }),
  makeProduct({
    name: "Everyday Tote Bag",
    description: "Structured tote designed for work and errands with enough room for daily essentials and a laptop.",
    price: 2199,
    category: "Accessories",
    subCategory: "Bag",
    collection: "Women",
    brand: "Carryfolk",
    sku: "ACC-BAG-023",
    stock: 16,
    sizes: ["Large"],
    tags: ["tote", "work bag", "daily"],
    specifications: [
      { key: "Material", value: "Vegan leather" },
      { key: "Laptop Fit", value: "Fits up to 14-inch" },
    ],
    images: [
      image("photo-1542291026-7eec264c27ff"),
      image("photo-1524498250077-390f9e378fc0"),
    ],
  }),
  makeProduct({
    name: "Polarized Sunglasses",
    description: "Lightweight sunglasses with polarized lenses and a clean frame profile for everyday wear.",
    price: 1899,
    category: "Accessories",
    subCategory: "Eyewear",
    collection: "Unisex",
    brand: "Suntrail",
    sku: "ACC-EYE-024",
    stock: 31,
    sizes: ["Standard"],
    tags: ["sunglasses", "summer", "polarized"],
    specifications: [
      { key: "Lens", value: "Polarized UV400" },
      { key: "Frame", value: "Acetate" },
    ],
    images: [
      image("photo-1511499767150-a48a237f0083"),
      image("photo-1572635196237-14b3f281503f"),
    ],
  }),
  makeProduct({
    name: "Layered Chain Set",
    description: "Multi-layer chain set with subtle shine for dressy and casual outfits alike.",
    price: 1299,
    category: "Accessories",
    subCategory: "Jewellery",
    collection: "Women",
    brand: "Luna Studio",
    sku: "ACC-JWL-025",
    stock: 25,
    sizes: ["Adjustable"],
    tags: ["jewellery", "party", "gift"],
    specifications: [
      { key: "Finish", value: "Gold tone" },
      { key: "Closure", value: "Lobster clasp" },
    ],
    images: [
      image("photo-1617038220319-276d3cfab638"),
      image("photo-1611652022419-a9419f74343d"),
    ],
  }),
  makeProduct({
    name: "Compact Crossbody Bag",
    description: "Hands-free sling bag with smart compartments and elevated hardware for everyday movement.",
    price: 1999,
    category: "Accessories",
    subCategory: "Bag",
    collection: "Unisex",
    brand: "Carryfolk",
    sku: "ACC-BAG-026",
    stock: 19,
    sizes: ["Compact"],
    tags: ["crossbody", "travel", "urban"],
    specifications: [
      { key: "Material", value: "Water resistant fabric" },
      { key: "Pockets", value: "3 zip compartments" },
    ],
    images: [
      image("photo-1548036328-c9fa89d128fa"),
      image("photo-1542291026-7eec264c27ff"),
    ],
  }),
  makeProduct({
    name: "Silk Pattern Scarf",
    description: "Soft draped scarf with printed detail for layering, gifting, and seasonal styling.",
    price: 999,
    category: "Accessories",
    subCategory: "Scarf",
    collection: "Women",
    brand: "Luna Studio",
    sku: "ACC-SCF-027",
    stock: 23,
    sizes: ["One Size"],
    tags: ["scarf", "gift", "pattern"],
    specifications: [
      { key: "Fabric", value: "Silk blend" },
      { key: "Length", value: "180 cm" },
    ],
    images: [
      image("photo-1520903074185-8eca362b3dce"),
      image("photo-1529139574466-a303027c1d8b"),
    ],
  }),
  makeProduct({
    name: "Leather Belt Set",
    description: "Two-piece belt set with clean buckle finish for office and denim styling.",
    price: 1499,
    category: "Accessories",
    subCategory: "Belt",
    collection: "Men",
    brand: "Oak & Hide",
    sku: "ACC-BLT-028",
    stock: 18,
    sizes: ["32", "34", "36", "38"],
    tags: ["belt", "formal", "combo"],
    specifications: [
      { key: "Material", value: "Leather" },
      { key: "Buckle", value: "Brushed metal" },
    ],
    images: [
      image("photo-1624222247344-550fb60583dc"),
      image("photo-1553062407-98eeb64c6a62"),
    ],
  }),
  makeProduct({
    name: "Signature Cap",
    description: "Curved peak cap with adjustable strap and subtle embroidery for relaxed casual looks.",
    price: 799,
    category: "Accessories",
    subCategory: "Cap",
    collection: "Unisex",
    brand: "Basic Foundry",
    sku: "ACC-CAP-029",
    stock: 32,
    sizes: ["Adjustable"],
    tags: ["cap", "casual", "summer"],
    specifications: [
      { key: "Material", value: "Cotton twill" },
      { key: "Closure", value: "Adjustable back strap" },
    ],
    images: [
      image("photo-1521369909029-2afed882baee"),
      image("photo-1575428652377-a2d80e2277fc"),
    ],
  }),
  makeProduct({
    name: "Minimal Card Holder",
    description: "Slim profile card holder for quick-access essentials with tidy pocket-friendly design.",
    price: 899,
    category: "Accessories",
    subCategory: "Wallet",
    collection: "Unisex",
    brand: "Oak & Hide",
    sku: "ACC-WLT-030",
    stock: 29,
    sizes: ["Compact"],
    tags: ["minimal", "cards", "daily carry"],
    specifications: [
      { key: "Capacity", value: "6 cards" },
      { key: "Material", value: "Leather" },
    ],
    images: [
      image("photo-1553062407-98eeb64c6a62"),
      image("photo-1627123424574-724758594e93"),
    ],
  }),

  makeProduct({
    name: "Street Runner Sneakers",
    description: "Comfort-driven sneakers with cushioned sole and breathable upper for daily movement.",
    price: 2999,
    category: "Footwear",
    subCategory: "Sneakers",
    collection: "Men",
    brand: "StrideLab",
    sku: "FTW-SNK-031",
    stock: 20,
    sizes: ["7", "8", "9", "10", "11"],
    tags: ["sneakers", "daily wear", "comfort"],
    specifications: [
      { key: "Upper", value: "Mesh knit" },
      { key: "Sole", value: "EVA cushion sole" },
    ],
    images: [
      image("photo-1542291026-7eec264c27ff"),
      image("photo-1549298916-b41d501d3772"),
    ],
  }),
  makeProduct({
    name: "Classic Leather Loafers",
    description: "Polished loafers with refined shape and all-day comfort for office and occasion wear.",
    price: 3899,
    category: "Footwear",
    subCategory: "Loafers",
    collection: "Men",
    brand: "Monarch Step",
    sku: "FTW-LOF-032",
    stock: 12,
    sizes: ["7", "8", "9", "10"],
    tags: ["formal", "leather", "office"],
    specifications: [
      { key: "Upper", value: "Genuine leather" },
      { key: "Lining", value: "Soft inner lining" },
    ],
    images: [
      image("photo-1614252235316-8c857d38b5f4"),
      image("photo-1612817159949-195b6eb9e31a"),
    ],
  }),
  makeProduct({
    name: "City Walk Sandals",
    description: "Strappy sandals built for comfort, grip, and easy styling with dresses or co-ords.",
    price: 1899,
    category: "Footwear",
    subCategory: "Sandals",
    collection: "Women",
    brand: "Mellow Walk",
    sku: "FTW-SND-033",
    stock: 18,
    sizes: ["5", "6", "7", "8"],
    tags: ["sandals", "casual", "summer"],
    specifications: [
      { key: "Footbed", value: "Padded comfort" },
      { key: "Closure", value: "Buckle strap" },
    ],
    images: [
      image("photo-1562273138-f46be4ebdf33"),
      image("photo-1525966222134-fcfa99b8ae77"),
    ],
  }),
  makeProduct({
    name: "LiteBounce Trainers",
    description: "Lightweight trainers for workouts, walks, and all-day movement with airy support.",
    price: 3299,
    category: "Footwear",
    subCategory: "Sports Shoes",
    collection: "Women",
    brand: "StrideLab",
    sku: "FTW-SPT-034",
    stock: 17,
    sizes: ["5", "6", "7", "8", "9"],
    tags: ["training", "active", "lightweight"],
    specifications: [
      { key: "Upper", value: "Engineered knit" },
      { key: "Sole", value: "Shock absorb foam" },
    ],
    images: [
      image("photo-1542291026-7eec264c27ff"),
      image("photo-1460353581641-37baddab0fa2"),
    ],
  }),
  makeProduct({
    name: "Everyday Slides",
    description: "Easy slip-on slides with durable sole and all-day house-to-street comfort.",
    price: 1099,
    category: "Footwear",
    subCategory: "Slides",
    collection: "Unisex",
    brand: "Mellow Walk",
    sku: "FTW-SLD-035",
    stock: 26,
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["slides", "casual", "comfort"],
    specifications: [
      { key: "Material", value: "Molded EVA" },
      { key: "Use", value: "Indoor and outdoor" },
    ],
    images: [
      image("photo-1600185365483-26d7a4cc7519"),
      image("photo-1525966222134-fcfa99b8ae77"),
    ],
  }),
  makeProduct({
    name: "Kids Play Sneakers",
    description: "Supportive kids sneakers with easy fastening and durable grip for daily school play.",
    price: 1799,
    category: "Footwear",
    subCategory: "Sneakers",
    collection: "Kid",
    brand: "Mini Miles",
    sku: "FTW-K-SNK-036",
    stock: 21,
    sizes: ["1", "2", "3", "4"],
    tags: ["kids", "school", "durable"],
    specifications: [
      { key: "Closure", value: "Velcro strap" },
      { key: "Sole", value: "Rubber grip sole" },
    ],
    images: [
      image("photo-1514989940723-e8e51635b782"),
      image("photo-1503919545889-aef636e10ad4"),
    ],
  }),
  makeProduct({
    name: "Suede Ankle Boots",
    description: "Soft suede ankle boots with block heel and polished shape for elevated cold-weather looks.",
    price: 4299,
    category: "Footwear",
    subCategory: "Boots",
    collection: "Women",
    brand: "Monarch Step",
    sku: "FTW-BTS-037",
    stock: 10,
    sizes: ["5", "6", "7", "8"],
    tags: ["boots", "winter", "elevated"],
    specifications: [
      { key: "Material", value: "Suede upper" },
      { key: "Heel", value: "Block heel" },
    ],
    images: [
      image("photo-1543163521-1bf539c55dd2"),
      image("photo-1600185365926-3a2ce3cdb9eb"),
    ],
  }),
  makeProduct({
    name: "Canvas Casual Slip-ons",
    description: "Simple canvas slip-ons made for easy errands, college days, and relaxed weekends.",
    price: 1499,
    category: "Footwear",
    subCategory: "Slip-ons",
    collection: "Unisex",
    brand: "StrideLab",
    sku: "FTW-SLP-038",
    stock: 23,
    sizes: ["6", "7", "8", "9", "10"],
    tags: ["canvas", "slip-on", "light"],
    specifications: [
      { key: "Upper", value: "Canvas" },
      { key: "Insole", value: "Soft foam" },
    ],
    images: [
      image("photo-1525966222134-fcfa99b8ae77"),
      image("photo-1600185365926-3a2ce3cdb9eb"),
    ],
  }),

  makeProduct({
    name: "Nordic Table Lamp",
    description: "A minimal lamp with warm ambient light and clean silhouette for desks, side tables, and shelves.",
    price: 2799,
    category: "Home",
    subCategory: "Lighting",
    collection: "General",
    brand: "Casa North",
    sku: "HME-LMP-039",
    stock: 14,
    sizes: ["Standard"],
    tags: ["decor", "lighting", "minimal"],
    specifications: [
      { key: "Material", value: "Metal and fabric shade" },
      { key: "Bulb", value: "E27 compatible" },
    ],
    images: [
      image("photo-1505693416388-ac5ce068fe85"),
      image("photo-1513694203232-719a280e022f"),
    ],
  }),
  makeProduct({
    name: "Stoneware Dinner Set",
    description: "Elegant stoneware dining set for everyday meals and hosted dinners with timeless finish.",
    price: 4599,
    category: "Home",
    subCategory: "Dining",
    collection: "General",
    brand: "Casa North",
    sku: "HME-DIN-040",
    stock: 11,
    sizes: ["16-piece set"],
    tags: ["dining", "kitchen", "stoneware"],
    specifications: [
      { key: "Pieces", value: "16" },
      { key: "Microwave Safe", value: "Yes" },
    ],
    images: [
      image("photo-1496412705862-e0088f16f791"),
      image("photo-1504754524776-8f4f37790ca0"),
    ],
  }),
  makeProduct({
    name: "Textured Cushion Cover Set",
    description: "Soft textured cushion covers that instantly warm up sofas, chairs, and reading corners.",
    price: 1299,
    category: "Home",
    subCategory: "Soft Furnishing",
    collection: "General",
    brand: "Loom Nest",
    sku: "HME-CSN-041",
    stock: 26,
    sizes: ["Set of 2"],
    tags: ["cushion", "living room", "decor"],
    specifications: [
      { key: "Material", value: "Cotton blend" },
      { key: "Size", value: "16 x 16 inches" },
    ],
    images: [
      image("photo-1505693416388-ac5ce068fe85"),
      image("photo-1484101403633-562f891dc89a"),
    ],
  }),
  makeProduct({
    name: "Oak Finish Side Table",
    description: "Compact side table with clean form factor for corners, sofa edges, and bedside placement.",
    price: 3899,
    category: "Home",
    subCategory: "Furniture",
    collection: "General",
    brand: "Loom Nest",
    sku: "HME-FUR-042",
    stock: 9,
    sizes: ["One Size"],
    tags: ["furniture", "side table", "wood"],
    specifications: [
      { key: "Material", value: "Engineered wood" },
      { key: "Finish", value: "Oak finish" },
    ],
    images: [
      image("photo-1505693416388-ac5ce068fe85"),
      image("photo-1505693416388-ac5ce068fe85"),
    ],
  }),
  makeProduct({
    name: "Aroma Reed Diffuser",
    description: "A calming diffuser with long-lasting fragrance designed to freshen bedrooms and living spaces.",
    price: 999,
    category: "Home",
    subCategory: "Fragrance",
    collection: "General",
    brand: "Casa North",
    sku: "HME-FRG-043",
    stock: 30,
    sizes: ["120 ml"],
    tags: ["home fragrance", "gift", "calm"],
    specifications: [
      { key: "Fragrance", value: "White tea and cedar" },
      { key: "Duration", value: "Up to 45 days" },
    ],
    images: [
      image("photo-1515377905703-c4788e51af15"),
      image("photo-1513694203232-719a280e022f"),
    ],
  }),
  makeProduct({
    name: "Chef Series Knife Set",
    description: "Balanced kitchen knife set for prep, slicing, and everyday cooking with comfortable grip.",
    price: 3199,
    category: "Home",
    subCategory: "Kitchen",
    collection: "General",
    brand: "Forge Home",
    sku: "HME-KIT-044",
    stock: 13,
    sizes: ["5-piece set"],
    tags: ["kitchen", "knife", "cooking"],
    specifications: [
      { key: "Pieces", value: "5" },
      { key: "Steel", value: "Stainless steel" },
    ],
    images: [
      image("photo-1496116218417-1a781b1c416c"),
      image("photo-1504754524776-8f4f37790ca0"),
    ],
  }),

  makeProduct({
    name: "Hydra Glow Serum",
    description: "A lightweight hydrating serum that supports smoother texture and visible everyday glow.",
    price: 1499,
    category: "Beauty",
    subCategory: "Serum",
    collection: "General",
    brand: "Velvet Skin",
    sku: "BEA-SRM-045",
    stock: 28,
    sizes: ["30 ml"],
    tags: ["skincare", "hydration", "glow"],
    specifications: [
      { key: "Skin Type", value: "All skin types" },
      { key: "Hero Ingredient", value: "Hyaluronic acid" },
    ],
    images: [
      image("photo-1620916566398-39f1143ab7be"),
      image("photo-1571781418606-70265b9cce90"),
    ],
  }),
  makeProduct({
    name: "Matte Finish Lip Color",
    description: "Comfortable matte lip color with rich payoff and non-drying texture for long wear.",
    price: 799,
    category: "Beauty",
    subCategory: "Makeup",
    collection: "Women",
    brand: "Velvet Skin",
    sku: "BEA-MUP-046",
    stock: 36,
    sizes: ["Rose Nude", "Berry Red", "Brick Brown"],
    tags: ["lipstick", "makeup", "matte"],
    specifications: [
      { key: "Finish", value: "Matte" },
      { key: "Wear", value: "Long lasting" },
    ],
    images: [
      image("photo-1586495777744-4413f21062fa"),
      image("photo-1522335789203-aabd1fc54bc9"),
    ],
  }),
  makeProduct({
    name: "Scalp Care Shampoo",
    description: "Daily-use shampoo that gently cleanses while helping refresh roots and reduce dryness.",
    price: 699,
    category: "Beauty",
    subCategory: "Haircare",
    collection: "General",
    brand: "Root Ritual",
    sku: "BEA-HRC-047",
    stock: 31,
    sizes: ["250 ml"],
    tags: ["haircare", "cleanse", "daily"],
    specifications: [
      { key: "Hair Type", value: "Normal to oily" },
      { key: "Free From", value: "Parabens" },
    ],
    images: [
      image("photo-1625772452859-1c03d5bf1137"),
      image("photo-1571781418606-70265b9cce90"),
    ],
  }),
  makeProduct({
    name: "Daily Defense Sunscreen",
    description: "Broad-spectrum sunscreen with light texture and no-white-cast finish for daily wear.",
    price: 899,
    category: "Beauty",
    subCategory: "Sun Care",
    collection: "General",
    brand: "Velvet Skin",
    sku: "BEA-SUN-048",
    stock: 33,
    sizes: ["50 g"],
    tags: ["spf", "daily", "skincare"],
    specifications: [
      { key: "Protection", value: "SPF 50 PA++++" },
      { key: "Texture", value: "Gel cream" },
    ],
    images: [
      image("photo-1556228720-195a672e8a03"),
      image("photo-1620916566398-39f1143ab7be"),
    ],
  }),
  makeProduct({
    name: "Velvet Body Mist",
    description: "A soft body mist with fresh floral notes designed for quick refresh through the day.",
    price: 999,
    category: "Beauty",
    subCategory: "Fragrance",
    collection: "General",
    brand: "Aura Bloom",
    sku: "BEA-FRG-049",
    stock: 24,
    sizes: ["150 ml"],
    tags: ["mist", "fresh", "daily wear"],
    specifications: [
      { key: "Notes", value: "Pear blossom and musk" },
      { key: "Use", value: "Body and clothing" },
    ],
    images: [
      image("photo-1541643600914-78b084683601"),
      image("photo-1522335789203-aabd1fc54bc9"),
    ],
  }),
  makeProduct({
    name: "Nourish Night Cream",
    description: "A rich evening cream designed to replenish moisture and support overnight softness.",
    price: 1599,
    category: "Beauty",
    subCategory: "Moisturizer",
    collection: "General",
    brand: "Aura Bloom",
    sku: "BEA-MST-050",
    stock: 20,
    sizes: ["50 g"],
    tags: ["night care", "moisture", "cream"],
    specifications: [
      { key: "Skin Type", value: "Dry to combination" },
      { key: "Hero Ingredient", value: "Ceramides" },
    ],
    images: [
      image("photo-1571781418606-70265b9cce90"),
      image("photo-1620916566398-39f1143ab7be"),
    ],
  }),
];

const connectDb = async () => {
  if (!process.env.MONGODB_URI) {
    throw new Error("MONGODB_URI is missing");
  }

  await mongoose.connect(`${process.env.MONGODB_URI}/cartNOW`);
};

const seedProducts = async () => {
  await connectDb();

  const operations = products.map((product) => ({
    updateOne: {
      filter: { sku: product.sku },
      update: {
        $set: {
          ...product,
          date: new Date(),
        },
        $setOnInsert: {
          reviews: [],
        },
      },
      upsert: true,
    },
  }));

  await productModel.bulkWrite(operations);

  const counts = await productModel.aggregate([
    { $group: { _id: "$category", count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]);

  console.log(`Seeded ${products.length} products.`);
  console.table(counts);
};

seedProducts()
  .catch((error) => {
    console.error("Product seed failed:", error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
